# Generated by Django 3.0 on 2023-06-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='course_prior',
            field=models.CharField(default=1, max_length=100, verbose_name=''),
            preserve_default=False,
        ),
    ]
